[package]
name = "zkpasskey-crypto-modules"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "modules/common/crates/common" }
common-gadget = { path = "modules/common/crates/gadget" }

thiserror = { version = "2.0.12" }
serde = { version = "1.0.227", features = ["derive"] }

ark-groth16 = { version = "0.5.0" }
ark-ec = { version = "0.5.0" }
ark-ff = { version = "0.5.0" }
ark-poly = { version = "0.5.0" }
ark-r1cs-std = { version = "0.5.0" }
ark-relations = { version = "0.5.0" }
ark-std = { version = "0.5.0" }
ark-crypto-primitives = { version = "0.5.0" }
ark-bn254 = { version = "0.5.0" }
ark-ed-on-bn254 = { version = "0.5.0" }
ark-serialize = { version = "0.5.0" }
memmap2 = { version = "0.9.8" }
once_cell = { version = "1.21.3" }

num = { version = "0.4" }
num-integer = { version = "0.1.46" }
num-bigint = { version = "0.4.6" }
num-traits = { version = "0.2.19" }

blake2 = { version = "0.10" }
dotenv = { version = "0.15" }
hex = { version = "0.4" }
rand = { version = "0.8" }
sha2 = { version = "0.10" }
